"""
svg-suite: Advanced SVG conversion nodes for ComfyUI
"""

from .svg_Advanced import NODE_CLASS_MAPPINGS as ADVANCED_NODE_MAPPINGS
from .svg_Advanced import NODE_DISPLAY_NAME_MAPPINGS as ADVANCED_DISPLAY_MAPPINGS
from .SVGCompression import NODE_CLASS_MAPPINGS as COMPRESS_NODE_MAPPINGS
from .SVGCompression import NODE_DISPLAY_NAME_MAPPINGS as COMPRESS_DISPLAY_MAPPINGS

# Merge the node mappings
NODE_CLASS_MAPPINGS = {**ADVANCED_NODE_MAPPINGS, **COMPRESS_NODE_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**ADVANCED_DISPLAY_MAPPINGS, **COMPRESS_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
