"""
svg-suite: Advanced SVG conversion nodes for ComfyUI
"""

from .svg_Advanced import NODE_CLASS_MAPPINGS as ADVANCED_NODE_MAPPINGS
from .svg_Advanced import NODE_DISPLAY_NAME_MAPPINGS as ADVANCED_DISPLAY_MAPPINGS
from .SVGCompression import NODE_CLASS_MAPPINGS as COMPRESS_NODE_MAPPINGS
from .SVGCompression import NODE_DISPLAY_NAME_MAPPINGS as COMPRESS_DISPLAY_MAPPINGS
from .SVGreColor import NODE_CLASS_MAPPINGS as COLOR_NODE_MAPPINGS
from .SVGreColor import NODE_DISPLAY_NAME_MAPPINGS as COLOR_DISPLAY_MAPPINGS
from .SVGStyler import NODE_CLASS_MAPPINGS as STYLER_NODE_MAPPINGS
from .SVGStyler import NODE_DISPLAY_NAME_MAPPINGS as STYLER_DISPLAY_MAPPINGS
from .SVG_StringEdit import NODE_CLASS_MAPPINGS as STRING_EDIT_NODE_MAPPINGS
from .SVG_StringEdit import NODE_DISPLAY_NAME_MAPPINGS as STRING_EDIT_DISPLAY_MAPPINGS
from .SVGXMLParser import NODE_CLASS_MAPPINGS as XML_PARSER_NODE_MAPPINGS
from .SVGXMLParser import NODE_DISPLAY_NAME_MAPPINGS as XML_PARSER_DISPLAY_MAPPINGS

# Merge the node mappings
NODE_CLASS_MAPPINGS = {
    **ADVANCED_NODE_MAPPINGS, 
    **COMPRESS_NODE_MAPPINGS, 
    **COLOR_NODE_MAPPINGS,
    **STYLER_NODE_MAPPINGS,
    **STRING_EDIT_NODE_MAPPINGS,
    **XML_PARSER_NODE_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **ADVANCED_DISPLAY_MAPPINGS, 
    **COMPRESS_DISPLAY_MAPPINGS, 
    **COLOR_DISPLAY_MAPPINGS,
    **STYLER_DISPLAY_MAPPINGS,
    **STRING_EDIT_DISPLAY_MAPPINGS,
    **XML_PARSER_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
